name: Build Firmware

on:
  push:
    branches: [ ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [esp32dev, esp32-s3-devkitc-1-16m]  # Указываем цели для сборки

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build firmware for ${{ matrix.env_name }}
        run: platformio run --environment ${{ matrix.env_name }}

      - name: Collect artifacts for ${{ matrix.env_name }}
        run: |
          mkdir -p artifacts/${{ matrix.env_name }}
          cp -r build/${{ matrix.env_name }}/* artifacts/${{ matrix.env_name }}/ || echo "No files to copy"

      - name: Upload artifacts for ${{ matrix.env_name }}
        uses: actions/upload-artifact@v3
        with:
          name: firmware-artifacts-${{ matrix.env_name }}
          path: artifacts/${{ matrix.env_name }}/
