name: Build images

on:
  push:
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy the stuff
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }} 

      - name: Build and push Platformio builder to Docker registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/platformio-builder:latest

      - name: Build and push SvelteESP32 builder to Docker registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./web
          file: ./web/Dockerfile
          tags: ${{ secrets.DOCKER_USER }}/sveltesp32-builder:latest